version: '3.8'

services:
  # --- Banco Relacional (Fonte da Verdade) ---
  postgres:
    image: postgres:15-alpine
    container_name: bt_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: blue_taurus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # --- Motor de Busca (Logs & Analytics) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: bt_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false    # Desativado para facilitar DEV local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  # --- Interface Visual (Opcional - para debug) ---
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: bt_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  elastic_data:
